---
# The root directory where the MDD Data is stored
mdd_data_root: "{{ lookup('env', 'PWD') }}/mdd-data"
# directory where logstash and filebeat lives
mdd_telemetry: "{{ lookup('env', 'PWD') }}/telemetry/elastic"
# The directory items that make up the direct path
# from the highest level to the device specific level
mdd_dir_items: >-
  {{ ((regions + sites) | intersect(group_names)) +
  [ inventory_hostname ] }}
# The data directory for the particular device
mdd_device_dir: >-
  {{ mdd_data_root }}/{{ mdd_dir_items | join('/') }}
# The file pattern for files that specify OD Data
mdd_oc_patterns:
  - 'oc-*.yml'
  - 'oc-*.yaml'
# The file pattern for files that specify state checks
# The data types that MDD will operate on
mdd_data_types:
  - oc
  - config
mdd_check_patterns:
  - 'check-*.yml'
# default file location for JSON schemas
mdd_schema_root: "{{ lookup('env', 'PWD') }}/schemas"
# The file pattern for files that specify data validation
mdd_validate_patterns:
  - 'validate-*.yml'
